import "./globals.css";

import type { ReactNode } from "react";

import type { Metadata } from "next";

import RootProviders from "./RootProviders";

const description = "Generated by create next app";

export const metadata: Metadata = {
  title: {
    default: "Spotify",
    template: "%s - Spotify"
  },
  description,
  authors: [{ name: "Adrian Piątek", url: "https://adrian-piatek-portfolio.vercel.app/" }],
  keywords: ["Next.js", "React", "TypeScript", "GraphQL", "Redux Toolkit", "Tailwind CSS"],
  openGraph: {
    title: { default: "Spotify", template: "%s - Spotify" },
    description,
    authors: ["Adrian Piątek"]
  },
  twitter: {
    card: "summary_large_image",
    title: {
      default: "Spotify",
      template: "%s - Spotify"
    },
    description
  }
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@200;300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <RootProviders>{children}</RootProviders>
      </body>
    </html>
  );
}
